[tox]
envlist =
    py{310,311,312}-dj42-{grp,nogrp}
    py{310,311,312}-dj50-{grp,nogrp}
    py{310,311,312,313}-dj51-{grp,nogrp}
    py{310,311,312,313}-dj52-{grp,nogrp}
    py312-dj52-migrations
    py312-dj52-noxmp
skipsdist = true

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[gh-actions:env]
DJANGO =
    4.2: dj42
    5.0: dj50
    5.1: dj51
    5.2: dj52
GRAPPELLI =
    0: nogrp
    1: grp

[testenv]
commands =
    pytest --junitxml={toxinidir}/reports/test-{envname}.xml {posargs}
usedevelop = True
setenv =
    COVERAGE_FILE={toxworkdir}/coverage/.coverage.{envname}
    migrations: CROPDUSTER_TEST_MIGRATIONS=1
passenv =
    CI
    DEFAULT_FILE_STORAGE
    AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY
    S3
deps =
    -e .
    pytest
    pytest-cov
    pytest-django
    selenium
    django-selenosis
    boto3
    ipdb
    coverage
    django-polymorphic
    django-storages
    dj42: Django>=4.2,<4.3
    dj50: Django>=5.0,<5.1
    dj51: Django>=5.1,<5.2
    dj52: Django>=5.2,<5.3
    dj42-grp: django-grappelli>=3.0,<3.1
    dj50-grp: django-grappelli>=4.0,<4.1
    dj51-grp: django-grappelli>=4.0,<4.1
    dj52-grp: django-grappelli>=4.0,<4.1
    lxml
    -e git+https://github.com/theatlantic/django-ckeditor.git@v4.5.7+atl.8.5\#egg=django-ckeditor
    !noxmp: -e git+https://github.com/python-xmp-toolkit/python-xmp-toolkit.git\#egg=python-xmp-toolkit

[testenv:py312-dj52-noxmp]
setenv =
    {[testenv]setenv}
    DJANGO_SETTINGS_MODULE=tests.settings_noxmp
commands =
    pytest --junitxml={toxinidir}/reports/test-{envname}.xml \
        tests/test_noxmp.py {posargs}

[testenv:coverage-report]
skip_install = true
deps = coverage
setenv=COVERAGE_FILE=.coverage
changedir = {toxworkdir}/coverage
commands =
    coverage combine
    coverage report
    coverage xml

[testenv:codecov]
skip_install = true
deps = codecov
depends = coverage-report
passenv = CODECOV_TOKEN
changedir = {toxinidir}
commands =
    codecov --file {toxworkdir}/coverage/coverage.xml {posargs}
