/**
 * Run the 4.x global API against HTML generated by Django and verify the DOM
 * writes expected by named downstream callers.
 */

import {
  afterEach,
  beforeAll,
  beforeEach,
  describe,
  expect,
  it,
  vi,
} from "vitest";
import jQuery from "jquery";

import {
  complete,
  createThumbnails,
  installGlobalApi,
  registerInput,
  removeSize,
  restoreSize,
  setThumbnails,
  show,
} from "./globalApi";
import { UPDATE_EVENT } from "./events";
import { defineWidgetElement } from "../dom/CropDusterWidgetElement";
import { registry } from "../dom/registry";
import type { LegacyCompletePayload } from "../formset/legacyPayload";
import {
  cardQuery,
  cardQueryAll,
  cleanupDocument,
  flush,
  setViewport,
  waitFor,
  waitForWidget,
} from "../testing/fixtures";
import { loadFixture } from "../testing/htmlFixtures";
import { recordWrites } from "../testing/writeLog";

const globals = globalThis as unknown as Record<string, unknown>;

const NEW_IMAGE = "article/lead_image/2026/09/new/original.jpg";
const NEW_PREVIEW = "/media/article/lead_image/2026/09/new/_preview.jpg";
const RENDERED_PREVIEW =
  "https://thumb.example.com/unsafe/fit-in/800x500/media/article/lead_image/2026/09/new/original.jpg";
const PREVIEW_SRCSET = `${RENDERED_PREVIEW}, https://thumb.example.com/unsafe/fit-in/1600x1000/media/article/lead_image/2026/09/new/original.jpg 2x`;
const RENDERED_MAIN =
  "https://thumb.example.com/unsafe/0x0:1300x1040/600x480/media/article/lead_image/2026/09/new/original.jpg";
const MAIN_SRCSET = `${RENDERED_MAIN}, https://thumb.example.com/unsafe/0x0:1300x1040/1200x960/media/article/lead_image/2026/09/new/original.jpg 2x`;

beforeAll(() => {
  defineWidgetElement();
  installGlobalApi();
});

beforeEach(() => {
  window.history.replaceState({}, "", "/admin/tests/article/1/change/");
});

afterEach(async () => {
  await cleanupDocument();
  delete globals.django;
  delete globals.grp;
  delete globals.jQuery;
  delete globals.$;
  vi.restoreAllMocks();
});

function cropPayload(): LegacyCompletePayload {
  return {
    crop: {
      image_id: 9,
      orig_image: NEW_IMAGE,
      orig_w: 674,
      orig_h: 800,
      thumbs: {
        main: {
          id: 41,
          name: "main",
          width: 600,
          height: 480,
          url: "/media/article/lead_image/2026/09/new/main.jpg",
        },
        thumb: {
          id: 42,
          name: "thumb",
          width: 110,
          height: 90,
          url: "/media/article/lead_image/2026/09/new/thumb.jpg",
        },
      },
    },
    thumbs: [],
    initial: true,
    preview_url: NEW_PREVIEW,
    preview_w: 421,
    preview_h: 500,
  };
}

describe("complete", () => {
  it("writes, rebuilds the options, renders and dispatches, in that order", async () => {
    globals.django = { jQuery };
    const fixture = loadFixture("article_change_lead_and_alt");
    await waitForWidget(fixture.root("lead_image"));
    const log = recordWrites(fixture.root("lead_image"));

    // The event is the last thing 4.x did, and downstream handlers read the
    // formset back out of the DOM when it fires.
    document.addEventListener(UPDATE_EVENT, () => {
      log.entries.push(
        `event ${fixture.field("lead_image", "id").value} ` +
          `${fixture.field("lead_image", "image").value} ` +
          `${fixture.root("lead_image").querySelectorAll("option").length}`,
      );
    });

    complete("lead_image", cropPayload());
    log.stop();

    expect(log.entries).toEqual([
      "value lead_image-0-id=9",
      `value lead_image-0-image=${NEW_IMAGE}`,
      `value lead_image=${NEW_IMAGE}`,
      "value lead_image-TOTAL_FORMS=1",
      "option -1",
      "option -2",
      "option -3",
      "option +41",
      "option +42",
      `event 9 ${NEW_IMAGE} 2`,
    ]);
  });

  it("fires cropduster:update on every jQuery instance, positionally", async () => {
    const grpJQuery = jQuery.noConflict(true) as unknown as typeof jQuery;
    globals.django = { jQuery };
    globals.grp = { jQuery: grpJQuery };
    const fixture = loadFixture("article_change_lead_and_alt");
    await waitForWidget(fixture.root("lead_image"));

    const calls: [string, string, unknown][] = [];
    for (const [name, $] of [
      ["django", jQuery],
      ["grp", grpJQuery],
    ] as const) {
      $(document).on(UPDATE_EVENT, (_event, prefix: string, data: unknown) => {
        calls.push([name, prefix, data]);
      });
    }
    const native: unknown[] = [];
    document.addEventListener(UPDATE_EVENT, (event) => {
      native.push((event as CustomEvent).detail);
    });

    const data = cropPayload();
    complete("lead_image", data);

    // Both channels reach a jQuery handler: it is bound through
    // addEventListener, so the native dispatch arrives first with no
    // positional arguments, and the explicit trigger follows with them.
    expect(calls.filter(([, prefix]) => prefix === "lead_image")).toEqual([
      ["django", "lead_image", data],
      ["grp", "lead_image", data],
    ]);
    expect(native).toEqual([{ prefix: "lead_image", data }]);
  });

  it("stores optional renderer media without changing the legacy payload", async () => {
    const fixture = loadFixture("article_change_lead_and_alt");
    await waitForWidget(fixture.root("lead_image"));

    const data = cropPayload();
    data.crop.orig_w = 1300;
    data.crop.orig_h = 1040;
    data.preview_w = 625;
    data.preview_h = 500;
    complete("lead_image", data, {
      preview: { url: RENDERED_PREVIEW, srcset: PREVIEW_SRCSET },
      thumbs: {
        main: { url: RENDERED_MAIN, srcset: MAIN_SRCSET },
      },
    });

    const images = fixture
      .root("lead_image")
      .querySelector<HTMLElement>(".cropduster-images")!;
    const preview = await waitFor(
      () => cardQuery<HTMLImageElement>(images, ".cropduster-image-thumb"),
      { message: "the renderer preview to render" },
    );
    const crop = cardQuery<HTMLImageElement>(images, ".cropduster-crop-thumb")!;
    const main = fixture
      .field("lead_image", "thumbs")
      .querySelector<HTMLOptionElement>('option[value="41"]')!;

    expect(preview.getAttribute("src")).toBe(RENDERED_PREVIEW);
    expect(preview.getAttribute("srcset")).toBe(PREVIEW_SRCSET);
    expect(crop.getAttribute("src")).toBe(RENDERED_MAIN);
    expect(crop.getAttribute("srcset")).toBe(MAIN_SRCSET);
    expect(main.getAttribute("data-url")).toBe(data.crop.thumbs.main?.url);
    expect(main.getAttribute("data-renderer-url")).toBe(RENDERED_MAIN);
    expect(main.getAttribute("data-renderer-srcset")).toBe(MAIN_SRCSET);
    expect(
      registry.byPrefix("lead_image")?.bridge.getSnapshot().preview,
    ).toEqual({
      url: NEW_PREVIEW,
      rendererUrl: RENDERED_PREVIEW,
      srcset: PREVIEW_SRCSET,
      width: "625",
      height: "500",
    });
  });

  it("adopts hand-built markup that has no widget element", async () => {
    const fixture = loadFixture("author_add_headshot");
    fixture.host("headshot").remove();
    await flush();
    expect(registry.byPrefix("headshot")).toBeNull();

    complete("headshot", cropPayload());
    await waitForWidget(fixture.root("headshot"));

    expect(registry.byPrefix("headshot")).not.toBeNull();
    expect(fixture.field("headshot", "id").value).toBe("9");
    expect(
      cardQuery(
        fixture
          .root("headshot")
          .querySelector<HTMLElement>(".cropduster-images")!,
        ".cropduster-image-thumb",
      ),
    ).not.toBeNull();
  });
});

describe("setThumbnails and createThumbnails", () => {
  it("round-trips into the markup 4.x's jsrender template emitted", async () => {
    const fixture = loadFixture("article_change_lead_and_alt");
    await waitForWidget(fixture.root("alt_image"));

    // A downstream script calls setThumbnails directly, with the thumbs of
    // an article it just pulled through its iframe.
    setThumbnails("alt_image", {
      wide: {
        id: 77,
        name: "wide",
        width: 600,
        height: 300,
        url: "/media/article/alt_image/2026/09/new/wide.jpg",
      },
    });

    const select = fixture.field("alt_image", "thumbs");
    expect(select.outerHTML).toContain(
      '<option value="77" data-width="600" data-height="300" ' +
        'data-url="/media/article/alt_image/2026/09/new/wide.jpg" ' +
        'data-tmp-file="true" selected="selected">wide</option>',
    );

    // Another downstream script reads them straight back from the options,
    // so the attribute spelling is the interface.
    const option = select.querySelector("option")!;
    expect(option.value).toBe("77");
    expect(option.selected).toBe(true);
    expect(option.innerHTML).toBe("wide");

    // Nothing renders until there is an original to render a preview of.
    const images = fixture
      .root("alt_image")
      .querySelector<HTMLElement>(".cropduster-images")!;
    expect(cardQuery(images, ".cropduster-card")).toBeNull();

    fixture.field("alt_image", "image").value = NEW_IMAGE;
    setPreviewData(fixture.field("alt_image", ""), {
      previewUrl: NEW_PREVIEW,
      previewW: 421,
      previewH: 500,
    });
    createThumbnails("alt_image");
    await waitFor(() => cardQuery(images, "a"), {
      message: "the preview to render",
    });

    // The summary card supersedes 4.x's jsrender markup; inside it, the
    // preview anchor keeps the classes and nesting that markup rendered.
    const anchor = cardQuery<HTMLAnchorElement>(images, "a")!;
    expect(anchor.className).toBe("cropduster-image cropduster-image-preview");
    expect(anchor.getAttribute("href")).toBe(NEW_PREVIEW);
    const img = anchor.querySelector("img")!;
    expect(img.className).toBe(
      "cropduster-image-thumb cropduster-image-thumb-preview",
    );
    expect(img.getAttribute("src")).toBe(NEW_PREVIEW);
    expect(img.getAttribute("width")).toBe("421");
    expect(img.getAttribute("height")).toBe("500");
  });

  it("re-renders a mounted widget from the current formset", async () => {
    const fixture = loadFixture("article_change_lead_and_alt");
    await waitForWidget(fixture.root("lead_image"));
    const images = fixture
      .root("lead_image")
      .querySelector<HTMLElement>(".cropduster-images")!;
    const before = cardQuery(images, "a")!.getAttribute("href");
    expect(before).toBe("/media/article/lead_image/{Y}/{m}/img/_preview.jpg");

    setPreviewData(fixture.field("lead_image", ""), {
      previewUrl: NEW_PREVIEW,
    });
    createThumbnails("lead_image");
    await waitFor(
      () => cardQuery(images, "a")?.getAttribute("href") === NEW_PREVIEW,
      { message: "the preview to re-render" },
    );

    expect(cardQuery(images, "a")!.getAttribute("href")).toBe(NEW_PREVIEW);
    expect(cardQueryAll(images, "a")).toHaveLength(1);
  });
});

/** Set the `data-*` attributes a fresh page load supplies the preview from. */
function setPreviewData(el: Element, data: Record<string, unknown>) {
  for (const [key, value] of Object.entries(data)) {
    const attribute = `data-${key.replace(/[A-Z]/g, "-$&").toLowerCase()}`;
    el.setAttribute(attribute, String(value));
  }
}

describe("removeSize and restoreSize", () => {
  it("mutates the array a downstream consumer retains", async () => {
    globals.django = { jQuery };
    const fixture = loadFixture("article_change_lead_and_alt");
    await waitForWidget(fixture.root("lead_image"));

    // One downstream script replaces the whole array on a layout change;
    // every later reader has to see that replacement, and another then
    // splices it through removeSize/restoreSize.
    const layout = [
      { name: "main", w: 600, h: 480 },
      { name: "thumb", w: 110, h: 90 },
      { name: "no_height", w: 600, h: null },
    ];
    jQuery(fixture.field("lead_image", "")).data("sizes", layout);
    const consumer = jQuery(fixture.field("lead_image", "")).data(
      "sizes",
    ) as typeof layout;
    expect(consumer).toBe(layout);

    removeSize("lead_image", "thumb");

    expect(consumer.map((size) => size.name)).toEqual(["main", "no_height"]);
    expect(jQuery(fixture.field("lead_image", "")).data("sizes")).toBe(layout);

    restoreSize("lead_image", "thumb");

    expect(consumer.map((size) => size.name)).toEqual([
      "main",
      "thumb",
      "no_height",
    ]);
    expect(jQuery(fixture.field("lead_image", "")).data("sizes")).toBe(layout);
  });

  it("reads the size list the template rendered when nothing replaced it", async () => {
    globals.django = { jQuery };
    const fixture = loadFixture("article_change_lead_and_alt");
    await waitForWidget(fixture.root("lead_image"));

    // The list is the parents only; `thumb` rides on `main.auto`, which is
    // what makes a size name a valid argument to removeSize but an auto name
    // not one.
    const bridge = registry.byPrefix("lead_image")!.bridge;
    expect(bridge.readSizes().map((size) => size.name)).toEqual([
      "main",
      "no_height",
    ]);

    removeSize("lead_image", "main");
    expect(bridge.readSizes().map((size) => size.name)).toEqual(["no_height"]);

    restoreSize("lead_image", "main");
    expect(bridge.readSizes().map((size) => size.name)).toEqual([
      "main",
      "no_height",
    ]);
    expect(jQuery(fixture.field("lead_image", "")).data("sizes")).toBe(
      bridge.readSizes(),
    );
  });
});

describe("show", () => {
  it("opens 4.x's popup URL from the rendered formset", async () => {
    // The rendered config is `auto`; a viewport this size resolves it to
    // the popup, matching a downstream editor's 830x550 iframe.
    const restore = setViewport(830, 550);
    const fixture = loadFixture("article_change_lead_and_alt");
    await waitForWidget(fixture.root("lead_image"));
    const focus = vi.fn();
    const open = vi
      .spyOn(window, "open")
      .mockReturnValue({ focus } as unknown as Window);

    fixture
      .root("lead_image")
      .querySelector<HTMLElement>("a.cropduster-customfield")!
      .click();

    const [url, name, features] = open.mock.calls[0]!;
    expect(name).toBe("lead_image");
    expect(features).toBe("height=650,width=960,resizable=yes,scrollbars=yes");
    expect(url).toContain("/cropduster/?pop=1");
    expect(url).toContain(
      "&image=article/lead_image/%7BY%7D/%7Bm%7D/img/original.jpg",
    );
    expect(url).toContain("&id=1");
    expect(url).toContain("&thumbs=1,2,3");
    expect(url).toContain("&el_id=lead_image");
    expect(url).toContain("&upload_to=article/lead_image/%25Y/%25m");
    expect(focus).toHaveBeenCalledTimes(1);
    restore();
  });

  it("mangles the window name of a nested prefix as 4.x did", async () => {
    const fixture = loadFixture("article_change_lead_and_alt");
    await waitForWidget(fixture.root("lead_image"));
    const open = vi
      .spyOn(window, "open")
      .mockReturnValue({ focus: vi.fn() } as unknown as Window);

    show("section_set-0-items-1-image", "/cropduster/?pop=1");

    expect(open.mock.calls[0]![1]).toBe(
      "section_set____0____items____1____image",
    );
  });
});

describe("registerInput", () => {
  it("adopts a form whose markup predates the element, once", async () => {
    const fixture = loadFixture("author_add_headshot");
    fixture.host("headshot").remove();
    await flush();

    registerInput(fixture.field("headshot", ""));
    registerInput(fixture.field("headshot", ""));
    await waitForWidget(fixture.root("headshot"));

    expect(registry.byPrefix("headshot")).not.toBeNull();
    expect(
      fixture.root("headshot").querySelectorAll("cropduster-widget"),
    ).toHaveLength(1);
    expect(
      fixture.root("headshot").querySelectorAll(".cropduster-button"),
    ).toHaveLength(1);
  });

  it("refuses to adopt an empty-form template", async () => {
    const fixture = loadFixture("nested_empty_item");
    const prefix = "section_set-empty-items-__prefix__-image";
    fixture.host(prefix).remove();
    await flush();

    registerInput(fixture.field(prefix, ""));
    await flush();

    expect(registry.all()).toHaveLength(0);
  });
});
