/**
 * Load widget HTML generated by `tests/test_widget_html.py`.
 *
 * The files retain placeholders for the changing CSRF token and the
 * date-expanded `upload_to` path.
 */

import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const FIXTURE_DIR = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../../tests/fixtures",
);

/**
 * The three renderings pinned on the Python side.
 *
 * - `author_add_headshot`: one field, unbound add form, no image.
 * - `article_change_lead_and_alt`: two fields on a bound change form, one with
 *   a saved image, three thumb options and a DELETE checkbox.
 * - `nested_empty_item`: the two fields of a nested inline's empty-form
 *   template, whose prefixes are the placeholders nothing may mount on.
 */
export type FixtureName =
  "author_add_headshot" | "article_change_lead_and_alt" | "nested_empty_item";

/** The prefixes each fixture's widgets are rendered at, in document order. */
export const FIXTURE_PREFIXES: Record<FixtureName, string[]> = {
  author_add_headshot: ["headshot"],
  article_change_lead_and_alt: ["lead_image", "alt_image"],
  nested_empty_item: [
    "section_set-empty-items-__prefix__-image",
    "section_set-empty-items-__prefix__-alt_image",
  ],
};

const cache = new Map<FixtureName, string>();

/** The raw file, comment header included. */
export function fixtureHtml(name: FixtureName): string {
  let html = cache.get(name);
  if (html === undefined) {
    html = readFileSync(resolve(FIXTURE_DIR, `${name}.html`), "utf8");
    cache.set(name, html);
  }
  return html;
}

export interface LoadedFixture {
  /** The element the markup was parsed into and appended to the document. */
  container: HTMLElement;
  /** Every `.cropduster-form` in the fixture, in document order. */
  roots: HTMLElement[];
  /** The `.cropduster-form` whose data field belongs to `prefix`. */
  root(prefix: string): HTMLElement;
  host(prefix: string): HTMLElement;
  /** A field of one widget's formset, by its unprefixed suffix. */
  field(prefix: string, suffix: string): HTMLInputElement;
  remove(): void;
}

function rootFor(roots: HTMLElement[], prefix: string): HTMLElement {
  const root = roots.find(
    (candidate) =>
      candidate
        .querySelector(".cropduster-data-field")
        ?.getAttribute("name") === prefix,
  );
  if (!root) {
    throw new Error(`no .cropduster-form for prefix ${prefix}`);
  }
  return root;
}

/** Parse a fixture into the document and return its parts. */
export function loadFixture(name: FixtureName): LoadedFixture {
  const container = document.createElement("div");
  container.innerHTML = fixtureHtml(name);
  document.body.appendChild(container);

  const roots = [
    ...container.querySelectorAll<HTMLElement>(".cropduster-form"),
  ];
  if (!roots.length) {
    throw new Error(`fixture ${name} rendered no .cropduster-form`);
  }

  return {
    container,
    roots,
    root: (prefix) => rootFor(roots, prefix),
    host(prefix) {
      const host = rootFor(roots, prefix).querySelector<HTMLElement>(
        "cropduster-widget",
      );
      if (!host) {
        throw new Error(`no <cropduster-widget> in ${prefix}`);
      }
      return host;
    },
    field(prefix, suffix) {
      const name = suffix ? `${prefix}-0-${suffix}` : prefix;
      const field = rootFor(roots, prefix).querySelector<HTMLInputElement>(
        `[name="${name}"]`,
      );
      if (!field) {
        throw new Error(`no [name="${name}"] in the fixture`);
      }
      return field;
    },
    remove: () => container.remove(),
  };
}
