# Generated by Django 5.2.17 on 2026-08-18 17:52

import cropduster.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lead_image', cropduster.fields.CropDusterImageField(blank=True, db_column='lead_image', default='', upload_to='img/articles/%Y')),
                ('alt_image', cropduster.fields.CropDusterImageField(blank=True, db_column='alt_image', default='', upload_to='img/articles/alt/%Y')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'galleries',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_width', models.PositiveIntegerField(blank=True, null=True)),
                ('video_height', models.PositiveIntegerField(blank=True, null=True)),
                ('still', cropduster.fields.CropDusterImageField(blank=True, db_column='still', default='', upload_to='img/videos/%Y')),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='example.page')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('image', cropduster.fields.CropDusterImageField(blank=True, db_column='image', default='', upload_to='img/pages/%Y')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='example.pagesection')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('image', cropduster.fields.CropDusterImageField(blank=True, db_column='image', default='', upload_to='img/galleries/%Y')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='example.gallery')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
